version: '2'
services:
  # Proxy to allow all our pieces to work together
  proxy:
    image: abiosoft/caddy
    ports:
      - "80:80"
    volumes:
      - ./configs/Caddyfile.dev:/etc/Caddyfile

  # Data
  db:
    image: postgres:9.5
    environment:
      - PGDATA=/var/lib/postgresql/data/app
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - /opt/hostedfactor/data/db:/var/lib/postgresql/data/app/
      - /opt/hostedfactor/storage/:/storage/
