# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.CharField(help_text='Encrypted user password', max_length=255)),
                ('last_login_attempt', models.DateTimeField()),
                ('failed_login_count', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
