# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogininfo',
            name='failed_login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlogininfo',
            name='last_login_attempt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
