# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20170129_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogininfo',
            name='credentials',
        ),
    ]
